image: ubuntu-ursa-master
 
test:
  stage: test
  script: 
    - "pytest"
  
  
build:
  stage: build
  script:
        - pip install -U twine
        - python setup.py sdist
        - twine upload dist/*
